spring:
  application:
    name:
  datasource:
    driverClassName: org.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/shop
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

server:
  port: 3306
